[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ose-core"
description = "Core library for OntoSpreadEd - Ontology spreadsheet editor"
requires-python = ">= 3.12"
version = "1.4.0"

dependencies = [
    "pandas",
    "openpyxl",
    "jsonschema",
    "daff",
    "whoosh",
    "networkx",
    "pydot",
    "py-horned-owl",
    "ontoutils",
    "pyyaml",
    "dacite",
    "aiohttp",
    "async-lru",
    "typing-extensions>=4.0",
    "urllib3",
    "GitHub-Flask",
    "Flask-SQLAlchemy==3.1.1",
    "Flask-Migrate",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["ose", "ose.*"]

[tool.setuptools.package-data]
"ose.database.migrations" = ["alembic.ini", "script.py.mako", "README"]
